# List of strings and integers
courses = ['Molecular biology', 'Bioinformatics', 'Genomics', 'Cell Biology']
courses_2 = ['Transcriptomics', 'Cancer Genomics']
print(courses)
print(len(courses))
print(courses[2])
print(courses[-1])
print(courses[0:3])
print(courses[:3])
print(courses[1:])
courses.append('Metagenomics')
print(courses)
courses.insert(2, 'Single cell genomics')
print(courses)
courses.extend(courses_2)
print(courses)
courses.remove('Cell Biology')
print(courses)
popped = courses.pop()
print(courses)
print(popped)
courses.reverse()
print(courses)
courses.sort()
print(courses)
courses.sort(reverse=True)
print(courses)
sorted_C = sorted(courses)
print(sorted_C)
numbers = [23, 9859, 53, 32523, 698, 23436] 
numbers.sort()
print(numbers)
numbers.sort(reverse=True)
print(numbers)
sorted_1 = sorted(numbers)
print(sorted_1)
print(min(numbers))
print(max(numbers))
print(sum(numbers))
print(courses.index('Bioinformatics'))
print('art' in courses)
print('Metagenomics' in courses)
for item in courses: 
    print(item)
for index,coursename in enumerate(courses):
    print(index, coursename)

